ENVIRONMENT:
  MAX_EPISODE_STEPS: 500

SIMULATOR:
  TYPE: 'Sim-0' # modified
  FORWARD_STEP_SIZE: 0.25
  TURN_ANGLE: 30
  TILT_ANGLE: 30
  ACTION_SPACE_CONFIG: "v1"
  AGENTS: ['AGENT_0']
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
    HEIGHT: 0.88
    RADIUS: 0.18
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: False
  SEMANTIC_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    POSITION: [0, 0.88, 0]
  RGB_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    POSITION: [0, 0.88, 0]
  DEPTH_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    MIN_DEPTH: 0.5
    MAX_DEPTH: 5.0
    POSITION: [0, 0.88, 0]
TASK:
  TYPE: ObjectNav-v1
  POSSIBLE_ACTIONS: ["STOP", "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT", "LOOK_UP", "LOOK_DOWN"]
  SUCCESS_DISTANCE: 1.0

  SENSORS: ['OBJECTGOAL_SENSOR', 'RGB_SENSOR', 'DEPTH_SENSOR', 'COMPASS_SENSOR', 'GPS_SENSOR', 'DEMONSTRATION_SENSOR', 'INFLECTION_WEIGHT_SENSOR']
  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL', 'SOFT_SPL', 'GOAL_OBJECT_VISIBLE'] #, 'TOP_DOWN_MAP']

  GOAL_SENSOR_UUID: objectgoal

  RGB_SENSOR:
    TYPE: "HabitatSimRGBSensor"
  DEPTH_SENSOR:
    TYPE: "HabitatSimDepthSensor"
  
  DEMONSTRATION_SENSOR:
    TYPE: DemonstrationSensor
  DEMONSTRATION_SENSOR_UUID: "demonstration"
  INFLECTION_WEIGHT_SENSOR:
    TYPE: InflectionWeightSensor
    INFLECTION_COEF: 3.477512060914205
  INFLECTION_WEIGHT_SENSOR_UUID: "inflection_weight"


  TOP_DOWN_MAP:
    DRAW_GOAL_AABBS: False
    DRAW_SHORTEST_PATH: False
    DARW_GOAL_VIEW_POINTS: False

  ROOM_VISITATION_MAP:
    TYPE: "RoomVisitationMap"
  EXPLORATION_METRICS:
    TYPE: "ExplorationMetrics"
  GOAL_OBJECT_VISIBLE:
    TYPE: "GoalObjectVisible"
    INSERTED_OBJECTS: False

  DISTANCE_TO_GOAL:
    TYPE: 'DistanceToGoal'
    DISTANCE_TO: VIEW_POINTS

  SUCCESS:
    SUCCESS_DISTANCE: 1.0
    THDA_SUCCESS_DISTANCE: 1.0
SEED: 103
DATASET:
  TYPE: UnifiedNav-v1
  SPLIT: train
  DATA_PATH: "/data/jing_li/habitat-lab/data/datasets/objectnav/mp3d/mp3d_70k/{split}/{split}.json.gz"
  OBJECTNAV_DATA_PATH: "/data/jing_li/habitat-lab/data/datasets/objectnav/mp3d/mp3d_70k/{split}/{split}.json.gz"
  VLN_DATA_PATH: ""
  SCENES_DIR: "/data/jing_li/habitat-lab/data/scene_datasets"
  MAX_REPLAY_STEPS: 500

